(define (problem drone_problem_d1_r1_l8_p8_c8_g8_ct3)(:domain logisticaSE)
(:objects
	dron1 - dron
	transportador1 - transportador
	n0 	n1 	n2 	n3 	n4  - num 
	deposito - loc
	Loc1 - loc
	Loc2 - loc
	Loc3 - loc
	Loc4 - loc
	Loc5 - loc
	Loc6 - loc
	Loc7 - loc
	Loc8 - loc
	caja1 - caja
	caja2 - caja
	caja3 - caja
	caja4 - caja
	caja5 - caja
	caja6 - caja
	caja7 - caja
	caja8 - caja
	food - contenido
	medicine - contenido
	bebida - contenido
	persona0 - persona
	persona1 - persona
	persona2 - persona
	persona3 - persona
	persona4 - persona
	persona5 - persona
	persona6 - persona
	persona7 - persona
)
(:init
	(loc-dron dron1 deposito)
	(loc-transportador transportador1 deposito)
	(persona-necesita-contenido persona1 food)
	(loc-persona persona1 Loc5)
	(persona-necesita-contenido persona1 medicine)
	(loc-persona persona1 Loc4)
	(persona-necesita-contenido persona1 bebida)
	(loc-persona persona1 Loc6)
	(persona-necesita-contenido persona2 medicine)
	(loc-persona persona2 deposito)
	(persona-necesita-contenido persona2 bebida)
	(loc-persona persona2 Loc3)
	(persona-necesita-contenido persona3 food)
	(loc-persona persona3 Loc3)
	(persona-necesita-contenido persona4 food)
	(loc-persona persona4 Loc6)
	(persona-necesita-contenido persona5 medicine)
	(loc-persona persona5 Loc6)
	(caja-contenido caja1 food)
	(loc-caja caja1 deposito)
	(caja-contenido caja2 medicine)
	(loc-caja caja2 deposito)
	(caja-contenido caja3 bebida)
	(loc-caja caja3 deposito)
	(caja-contenido caja4 medicine)
	(loc-caja caja4 deposito)
	(caja-contenido caja5 bebida)
	(loc-caja caja5 deposito)
	(caja-contenido caja6 food)
	(loc-caja caja6 deposito)
	(caja-contenido caja7 food)
	(loc-caja caja7 deposito)
	(caja-contenido caja8 medicine)
	(loc-caja caja8 deposito)
	(caja-free caja1)
	(caja-free caja2)
	(caja-free caja3)
	(caja-free caja4)
	(caja-free caja5)
	(caja-free caja6)
	(caja-free caja7)
	(caja-free caja8)
	(siguiente n0 n1) 
	(siguiente n1 n2) 
	(siguiente n2 n3) 
	(siguiente n3 n4) 
	(capacidad-actual transportador1 n0)
	(dron-free dron1)
	(=(fly-cost deposito deposito)1)
	(=(fly-cost deposito Loc1) 155)
	(=(fly-cost Loc1 deposito) 155)
	(=(fly-cost deposito Loc2) 244)
	(=(fly-cost Loc2 deposito) 244)
	(=(fly-cost deposito Loc3) 23)
	(=(fly-cost Loc3 deposito) 23)
	(=(fly-cost deposito Loc4) 113)
	(=(fly-cost Loc4 deposito) 113)
	(=(fly-cost deposito Loc5) 62)
	(=(fly-cost Loc5 deposito) 62)
	(=(fly-cost deposito Loc6) 82)
	(=(fly-cost Loc6 deposito) 82)
	(=(fly-cost deposito Loc7) 191)
	(=(fly-cost Loc7 deposito) 191)
	(=(fly-cost deposito Loc8) 194)
	(=(fly-cost Loc8 deposito) 194)
	(=(fly-cost Loc1 Loc2) 149)
	(=(fly-cost Loc2 Loc1) 149)
	(=(fly-cost Loc1 Loc3) 135)
	(=(fly-cost Loc3 Loc1) 135)
	(=(fly-cost Loc1 Loc4) 43)
	(=(fly-cost Loc4 Loc1) 43)
	(=(fly-cost Loc1 Loc5) 146)
	(=(fly-cost Loc5 Loc1) 146)
	(=(fly-cost Loc1 Loc6) 102)
	(=(fly-cost Loc6 Loc1) 102)
	(=(fly-cost Loc1 Loc7) 210)
	(=(fly-cost Loc7 Loc1) 210)
	(=(fly-cost Loc1 Loc8) 78)
	(=(fly-cost Loc8 Loc1) 78)
	(=(fly-cost Loc2 Loc3) 222)
	(=(fly-cost Loc3 Loc2) 222)
	(=(fly-cost Loc2 Loc4) 171)
	(=(fly-cost Loc4 Loc2) 171)
	(=(fly-cost Loc2 Loc5) 197)
	(=(fly-cost Loc5 Loc2) 197)
	(=(fly-cost Loc2 Loc6) 163)
	(=(fly-cost Loc6 Loc2) 163)
	(=(fly-cost Loc2 Loc7) 152)
	(=(fly-cost Loc7 Loc2) 152)
	(=(fly-cost Loc2 Loc8) 71)
	(=(fly-cost Loc8 Loc2) 71)
	(=(fly-cost Loc3 Loc4) 95)
	(=(fly-cost Loc4 Loc3) 95)
	(=(fly-cost Loc3 Loc5) 48)
	(=(fly-cost Loc5 Loc3) 48)
	(=(fly-cost Loc3 Loc6) 59)
	(=(fly-cost Loc6 Loc3) 59)
	(=(fly-cost Loc3 Loc7) 176)
	(=(fly-cost Loc7 Loc3) 176)
	(=(fly-cost Loc3 Loc8) 171)
	(=(fly-cost Loc8 Loc3) 171)
	(=(fly-cost Loc4 Loc5) 112)
	(=(fly-cost Loc5 Loc4) 112)
	(=(fly-cost Loc4 Loc6) 73)
	(=(fly-cost Loc6 Loc4) 73)
	(=(fly-cost Loc4 Loc7) 199)
	(=(fly-cost Loc7 Loc4) 199)
	(=(fly-cost Loc4 Loc8) 104)
	(=(fly-cost Loc8 Loc4) 104)
	(=(fly-cost Loc5 Loc6) 46)
	(=(fly-cost Loc6 Loc5) 46)
	(=(fly-cost Loc5 Loc7) 129)
	(=(fly-cost Loc7 Loc5) 129)
	(=(fly-cost Loc5 Loc8) 159)
	(=(fly-cost Loc8 Loc5) 159)
	(=(fly-cost Loc6 Loc7) 135)
	(=(fly-cost Loc7 Loc6) 135)
	(=(fly-cost Loc6 Loc8) 117)
	(=(fly-cost Loc8 Loc6) 117)
	(=(fly-cost Loc7 Loc8) 167)
	(=(fly-cost Loc8 Loc7) 167)
	(=(fly-cost Loc1 Loc1) 1)
	(=(fly-cost Loc1 Loc1) 1)
	(=(fly-cost Loc2 Loc2) 1)
	(=(fly-cost Loc2 Loc2) 1)
	(=(fly-cost Loc3 Loc3) 1)
	(=(fly-cost Loc3 Loc3) 1)
	(=(fly-cost Loc4 Loc4) 1)
	(=(fly-cost Loc4 Loc4) 1)
	(=(fly-cost Loc5 Loc5) 1)
	(=(fly-cost Loc5 Loc5) 1)
	(=(fly-cost Loc6 Loc6) 1)
	(=(fly-cost Loc6 Loc6) 1)
	(=(fly-cost Loc7 Loc7) 1)
	(=(fly-cost Loc7 Loc7) 1)
	(=(fly-cost Loc8 Loc8) 1)
	(=(fly-cost Loc8 Loc8) 1)
	(=(total-cost)0)
)
(:goal (and

	(loc-dron dron1 deposito)
	(persona-tiene-contenido persona1 food)
	(persona-tiene-contenido persona1 medicine)
	(persona-tiene-contenido persona1 bebida)
	(persona-tiene-contenido persona2 medicine)
	(persona-tiene-contenido persona2 bebida)
	(persona-tiene-contenido persona3 food)
	(persona-tiene-contenido persona4 food)
	(persona-tiene-contenido persona5 medicine)
	))
(:metric minimize(total-cost))

)
