(define (problem drone_problem_d1_r1_l8_p8_c8_g8_ct3)(:domain logisticaSE)
(:objects
	dron1 - dron
	transportador1 - transportador
	n0 	n1 	n2 	n3 	n4  - num 
	deposito - loc
	Loc1 - loc
	Loc2 - loc
	Loc3 - loc
	Loc4 - loc
	Loc5 - loc
	Loc6 - loc
	Loc7 - loc
	Loc8 - loc
	caja1 - caja
	caja2 - caja
	caja3 - caja
	caja4 - caja
	caja5 - caja
	caja6 - caja
	caja7 - caja
	caja8 - caja
	food - contenido
	medicine - contenido
	bebida - contenido
	persona0 - persona
	persona1 - persona
	persona2 - persona
	persona3 - persona
	persona4 - persona
	persona5 - persona
	persona6 - persona
	persona7 - persona
)
(:init
	(loc-dron dron1 deposito)
	(loc-transportador transportador1 deposito)
	(persona-necesita-contenido persona0 food)
	(loc-persona persona0 Loc6)
	(persona-necesita-contenido persona3 bebida)
	(loc-persona persona3 Loc6)
	(persona-necesita-contenido persona4 food)
	(loc-persona persona4 Loc5)
	(persona-necesita-contenido persona4 medicine)
	(loc-persona persona4 Loc4)
	(persona-necesita-contenido persona5 food)
	(loc-persona persona5 Loc6)
	(persona-necesita-contenido persona6 medicine)
	(loc-persona persona6 Loc7)
	(persona-necesita-contenido persona6 bebida)
	(loc-persona persona6 Loc6)
	(persona-necesita-contenido persona7 food)
	(loc-persona persona7 Loc3)
	(caja-contenido caja1 food)
	(loc-caja caja1 deposito)
	(caja-contenido caja2 bebida)
	(loc-caja caja2 deposito)
	(caja-contenido caja3 food)
	(loc-caja caja3 deposito)
	(caja-contenido caja4 medicine)
	(loc-caja caja4 deposito)
	(caja-contenido caja5 food)
	(loc-caja caja5 deposito)
	(caja-contenido caja6 medicine)
	(loc-caja caja6 deposito)
	(caja-contenido caja7 bebida)
	(loc-caja caja7 deposito)
	(caja-contenido caja8 food)
	(loc-caja caja8 deposito)
	(caja-free caja1)
	(caja-free caja2)
	(caja-free caja3)
	(caja-free caja4)
	(caja-free caja5)
	(caja-free caja6)
	(caja-free caja7)
	(caja-free caja8)
	(siguiente n0 n1) 
	(siguiente n1 n2) 
	(siguiente n2 n3) 
	(siguiente n3 n4) 
	(capacidad-actual transportador1 n0)
	(dron-free dron1)
	(=(fly-cost deposito deposito)1)
	(=(fly-cost deposito Loc1) 132)
	(=(fly-cost Loc1 deposito) 132)
	(=(fly-cost deposito Loc2) 36)
	(=(fly-cost Loc2 deposito) 36)
	(=(fly-cost deposito Loc3) 195)
	(=(fly-cost Loc3 deposito) 195)
	(=(fly-cost deposito Loc4) 75)
	(=(fly-cost Loc4 deposito) 75)
	(=(fly-cost deposito Loc5) 107)
	(=(fly-cost Loc5 deposito) 107)
	(=(fly-cost deposito Loc6) 239)
	(=(fly-cost Loc6 deposito) 239)
	(=(fly-cost deposito Loc7) 163)
	(=(fly-cost Loc7 deposito) 163)
	(=(fly-cost deposito Loc8) 154)
	(=(fly-cost Loc8 deposito) 154)
	(=(fly-cost Loc1 Loc2) 98)
	(=(fly-cost Loc2 Loc1) 98)
	(=(fly-cost Loc1 Loc3) 91)
	(=(fly-cost Loc3 Loc1) 91)
	(=(fly-cost Loc1 Loc4) 87)
	(=(fly-cost Loc4 Loc1) 87)
	(=(fly-cost Loc1 Loc5) 57)
	(=(fly-cost Loc5 Loc1) 57)
	(=(fly-cost Loc1 Loc6) 108)
	(=(fly-cost Loc6 Loc1) 108)
	(=(fly-cost Loc1 Loc7) 114)
	(=(fly-cost Loc7 Loc1) 114)
	(=(fly-cost Loc1 Loc8) 51)
	(=(fly-cost Loc8 Loc1) 51)
	(=(fly-cost Loc2 Loc3) 161)
	(=(fly-cost Loc3 Loc2) 161)
	(=(fly-cost Loc2 Loc4) 47)
	(=(fly-cost Loc4 Loc2) 47)
	(=(fly-cost Loc2 Loc5) 74)
	(=(fly-cost Loc5 Loc2) 74)
	(=(fly-cost Loc2 Loc6) 205)
	(=(fly-cost Loc6 Loc2) 205)
	(=(fly-cost Loc2 Loc7) 136)
	(=(fly-cost Loc7 Loc2) 136)
	(=(fly-cost Loc2 Loc8) 124)
	(=(fly-cost Loc8 Loc2) 124)
	(=(fly-cost Loc3 Loc4) 125)
	(=(fly-cost Loc4 Loc3) 125)
	(=(fly-cost Loc3 Loc5) 88)
	(=(fly-cost Loc5 Loc3) 88)
	(=(fly-cost Loc3 Loc6) 96)
	(=(fly-cost Loc6 Loc3) 96)
	(=(fly-cost Loc3 Loc7) 70)
	(=(fly-cost Loc7 Loc3) 70)
	(=(fly-cost Loc3 Loc8) 131)
	(=(fly-cost Loc8 Loc3) 131)
	(=(fly-cost Loc4 Loc5) 39)
	(=(fly-cost Loc5 Loc4) 39)
	(=(fly-cost Loc4 Loc6) 186)
	(=(fly-cost Loc6 Loc4) 186)
	(=(fly-cost Loc4 Loc7) 90)
	(=(fly-cost Loc7 Loc4) 90)
	(=(fly-cost Loc4 Loc8) 129)
	(=(fly-cost Loc8 Loc4) 129)
	(=(fly-cost Loc5 Loc6) 148)
	(=(fly-cost Loc6 Loc5) 148)
	(=(fly-cost Loc5 Loc7) 71)
	(=(fly-cost Loc7 Loc5) 71)
	(=(fly-cost Loc5 Loc8) 106)
	(=(fly-cost Loc8 Loc5) 106)
	(=(fly-cost Loc6 Loc7) 163)
	(=(fly-cost Loc7 Loc6) 163)
	(=(fly-cost Loc6 Loc8) 108)
	(=(fly-cost Loc8 Loc6) 108)
	(=(fly-cost Loc7 Loc8) 164)
	(=(fly-cost Loc8 Loc7) 164)
	(=(fly-cost Loc1 Loc1) 1)
	(=(fly-cost Loc1 Loc1) 1)
	(=(fly-cost Loc2 Loc2) 1)
	(=(fly-cost Loc2 Loc2) 1)
	(=(fly-cost Loc3 Loc3) 1)
	(=(fly-cost Loc3 Loc3) 1)
	(=(fly-cost Loc4 Loc4) 1)
	(=(fly-cost Loc4 Loc4) 1)
	(=(fly-cost Loc5 Loc5) 1)
	(=(fly-cost Loc5 Loc5) 1)
	(=(fly-cost Loc6 Loc6) 1)
	(=(fly-cost Loc6 Loc6) 1)
	(=(fly-cost Loc7 Loc7) 1)
	(=(fly-cost Loc7 Loc7) 1)
	(=(fly-cost Loc8 Loc8) 1)
	(=(fly-cost Loc8 Loc8) 1)
	(=(total-cost)0)
)
(:goal (and

	(loc-dron dron1 deposito)
	(persona-tiene-contenido persona0 food)
	(persona-tiene-contenido persona3 bebida)
	(persona-tiene-contenido persona4 food)
	(persona-tiene-contenido persona4 medicine)
	(persona-tiene-contenido persona5 food)
	(persona-tiene-contenido persona6 medicine)
	(persona-tiene-contenido persona6 bebida)
	(persona-tiene-contenido persona7 food)
	))
(:metric minimize(total-cost))

)
