(define (problem drone_problem_d1_r0_l30_p30_c30_g30_ct2)(:domain logisticaSE)
(:objects
	dron1 - dron
	deposito - loc
	A - loc
	B - loc
	C - loc
	D - loc
	E - loc
	F - loc
	G - loc
	H - loc
	I - loc
	J - loc
	K - loc
	L - loc
	M - loc
	N - loc
	O - loc
	P - loc
	Q - loc
	R - loc
	S - loc
	T - loc
	U - loc
	V - loc
	W - loc
	X - loc
	Y - loc
	Z - loc
	A0 - loc
	B0 - loc
	C0 - loc
	D0 - loc
	caja1 - caja
	caja2 - caja
	caja3 - caja
	caja4 - caja
	caja5 - caja
	caja6 - caja
	caja7 - caja
	caja8 - caja
	caja9 - caja
	caja10 - caja
	caja11 - caja
	caja12 - caja
	caja13 - caja
	caja14 - caja
	caja15 - caja
	caja16 - caja
	caja17 - caja
	caja18 - caja
	caja19 - caja
	caja20 - caja
	caja21 - caja
	caja22 - caja
	caja23 - caja
	caja24 - caja
	caja25 - caja
	caja26 - caja
	caja27 - caja
	caja28 - caja
	caja29 - caja
	caja30 - caja
	food - contenido
	medicine - contenido
	persona0 - persona
	persona1 - persona
	persona2 - persona
	persona3 - persona
	persona4 - persona
	persona5 - persona
	persona6 - persona
	persona7 - persona
	persona8 - persona
	persona9 - persona
	persona10 - persona
	persona11 - persona
	persona12 - persona
	persona13 - persona
	persona14 - persona
	persona15 - persona
	persona16 - persona
	persona17 - persona
	persona18 - persona
	persona19 - persona
	persona20 - persona
	persona21 - persona
	persona22 - persona
	persona23 - persona
	persona24 - persona
	persona25 - persona
	persona26 - persona
	persona27 - persona
	persona28 - persona
	persona29 - persona
	brazo1 - brazo
	brazo2 - brazo)
(:init
	(loc-dron dron1 Y)
	(persona-necesita-contenido persona0 food)
	(loc-persona persona0 B0)
	(caja-contenido caja1 food)
	(loc-caja caja1 B0)
	(persona-necesita-contenido persona1 medicine)
	(loc-persona persona1 R)
	(caja-contenido caja2 medicine)
	(loc-caja caja2 M)
	(persona-necesita-contenido persona2 medicine)
	(loc-persona persona2 L)
	(caja-contenido caja3 medicine)
	(loc-caja caja3 A)
	(persona-necesita-contenido persona4 food)
	(loc-persona persona4 D0)
	(caja-contenido caja4 food)
	(loc-caja caja4 Q)
	(persona-necesita-contenido persona5 medicine)
	(loc-persona persona5 S)
	(caja-contenido caja5 medicine)
	(loc-caja caja5 Y)
	(persona-necesita-contenido persona6 food)
	(loc-persona persona6 P)
	(caja-contenido caja6 food)
	(loc-caja caja6 S)
	(persona-necesita-contenido persona6 medicine)
	(loc-persona persona6 Y)
	(caja-contenido caja7 medicine)
	(loc-caja caja7 W)
	(persona-necesita-contenido persona7 food)
	(loc-persona persona7 W)
	(caja-contenido caja8 food)
	(loc-caja caja8 Y)
	(persona-necesita-contenido persona9 food)
	(loc-persona persona9 Q)
	(caja-contenido caja9 food)
	(loc-caja caja9 S)
	(persona-necesita-contenido persona9 medicine)
	(loc-persona persona9 L)
	(caja-contenido caja10 medicine)
	(loc-caja caja10 P)
	(persona-necesita-contenido persona10 food)
	(loc-persona persona10 X)
	(caja-contenido caja11 food)
	(loc-caja caja11 C0)
	(persona-necesita-contenido persona10 medicine)
	(loc-persona persona10 P)
	(caja-contenido caja12 medicine)
	(loc-caja caja12 U)
	(persona-necesita-contenido persona11 medicine)
	(loc-persona persona11 O)
	(caja-contenido caja13 medicine)
	(loc-caja caja13 X)
	(persona-necesita-contenido persona13 medicine)
	(loc-persona persona13 Q)
	(caja-contenido caja14 medicine)
	(loc-caja caja14 C0)
	(persona-necesita-contenido persona14 food)
	(loc-persona persona14 Y)
	(caja-contenido caja15 food)
	(loc-caja caja15 V)
	(persona-necesita-contenido persona14 medicine)
	(loc-persona persona14 Z)
	(caja-contenido caja16 medicine)
	(loc-caja caja16 D0)
	(persona-necesita-contenido persona16 food)
	(loc-persona persona16 F)
	(caja-contenido caja17 food)
	(loc-caja caja17 O)
	(persona-necesita-contenido persona19 medicine)
	(loc-persona persona19 N)
	(caja-contenido caja18 medicine)
	(loc-caja caja18 C)
	(persona-necesita-contenido persona20 food)
	(loc-persona persona20 V)
	(caja-contenido caja19 food)
	(loc-caja caja19 A)
	(persona-necesita-contenido persona20 medicine)
	(loc-persona persona20 Z)
	(caja-contenido caja20 medicine)
	(loc-caja caja20 X)
	(persona-necesita-contenido persona22 food)
	(loc-persona persona22 U)
	(caja-contenido caja21 food)
	(loc-caja caja21 C)
	(persona-necesita-contenido persona22 medicine)
	(loc-persona persona22 H)
	(caja-contenido caja22 medicine)
	(loc-caja caja22 B)
	(persona-necesita-contenido persona23 medicine)
	(loc-persona persona23 G)
	(caja-contenido caja23 medicine)
	(loc-caja caja23 R)
	(persona-necesita-contenido persona24 medicine)
	(loc-persona persona24 X)
	(caja-contenido caja24 medicine)
	(loc-caja caja24 H)
	(persona-necesita-contenido persona25 food)
	(loc-persona persona25 S)
	(caja-contenido caja25 food)
	(loc-caja caja25 R)
	(persona-necesita-contenido persona25 medicine)
	(loc-persona persona25 B0)
	(caja-contenido caja26 medicine)
	(loc-caja caja26 F)
	(persona-necesita-contenido persona27 food)
	(loc-persona persona27 A0)
	(caja-contenido caja27 food)
	(loc-caja caja27 B0)
	(persona-necesita-contenido persona27 medicine)
	(loc-persona persona27 S)
	(caja-contenido caja28 medicine)
	(loc-caja caja28 B0)
	(persona-necesita-contenido persona28 medicine)
	(loc-persona persona28 L)
	(caja-contenido caja29 medicine)
	(loc-caja caja29 N)
	(persona-necesita-contenido persona29 food)
	(loc-persona persona29 P)
	(caja-contenido caja30 food)
	(loc-caja caja30 V)
	(brazo-dron-free dron1 brazo1)
	(brazo-dron-free dron1 brazo2)
)
(:goal (and

	(loc-dron dron1 deposito)
	(persona-tiene-contenido persona0 food)
	(persona-tiene-contenido persona1 medicine)
	(persona-tiene-contenido persona2 medicine)
	(persona-tiene-contenido persona4 food)
	(persona-tiene-contenido persona5 medicine)
	(persona-tiene-contenido persona6 food)
	(persona-tiene-contenido persona6 medicine)
	(persona-tiene-contenido persona7 food)
	(persona-tiene-contenido persona9 food)
	(persona-tiene-contenido persona9 medicine)
	(persona-tiene-contenido persona10 food)
	(persona-tiene-contenido persona10 medicine)
	(persona-tiene-contenido persona11 medicine)
	(persona-tiene-contenido persona13 medicine)
	(persona-tiene-contenido persona14 food)
	(persona-tiene-contenido persona14 medicine)
	(persona-tiene-contenido persona16 food)
	(persona-tiene-contenido persona19 medicine)
	(persona-tiene-contenido persona20 food)
	(persona-tiene-contenido persona20 medicine)
	(persona-tiene-contenido persona22 food)
	(persona-tiene-contenido persona22 medicine)
	(persona-tiene-contenido persona23 medicine)
	(persona-tiene-contenido persona24 medicine)
	(persona-tiene-contenido persona25 food)
	(persona-tiene-contenido persona25 medicine)
	(persona-tiene-contenido persona27 food)
	(persona-tiene-contenido persona27 medicine)
	(persona-tiene-contenido persona28 medicine)
	(persona-tiene-contenido persona29 food)
	))
)
