(define (problem drone_problem_d1_r0_l22_p22_c22_g22_ct2)(:domain logisticaSE)
(:objects
	dron1 - dron
	deposito - loc
	A - loc
	B - loc
	C - loc
	D - loc
	E - loc
	F - loc
	G - loc
	H - loc
	I - loc
	J - loc
	K - loc
	L - loc
	M - loc
	N - loc
	O - loc
	P - loc
	Q - loc
	R - loc
	S - loc
	T - loc
	U - loc
	V - loc
	caja1 - caja
	caja2 - caja
	caja3 - caja
	caja4 - caja
	caja5 - caja
	caja6 - caja
	caja7 - caja
	caja8 - caja
	caja9 - caja
	caja10 - caja
	caja11 - caja
	caja12 - caja
	caja13 - caja
	caja14 - caja
	caja15 - caja
	caja16 - caja
	caja17 - caja
	caja18 - caja
	caja19 - caja
	caja20 - caja
	caja21 - caja
	caja22 - caja
	food - contenido
	medicine - contenido
	persona0 - persona
	persona1 - persona
	persona2 - persona
	persona3 - persona
	persona4 - persona
	persona5 - persona
	persona6 - persona
	persona7 - persona
	persona8 - persona
	persona9 - persona
	persona10 - persona
	persona11 - persona
	persona12 - persona
	persona13 - persona
	persona14 - persona
	persona15 - persona
	persona16 - persona
	persona17 - persona
	persona18 - persona
	persona19 - persona
	persona20 - persona
	persona21 - persona
	brazo1 - brazo
	brazo2 - brazo)
(:init
	(loc-dron dron1 deposito)
	(persona-necesita-contenido persona2 food)
	(loc-persona persona2 I)
	(caja-contenido caja1 food)
	(loc-caja caja1 L)
	(persona-necesita-contenido persona3 medicine)
	(loc-persona persona3 L)
	(caja-contenido caja2 medicine)
	(loc-caja caja2 F)
	(persona-necesita-contenido persona5 food)
	(loc-persona persona5 J)
	(caja-contenido caja3 food)
	(loc-caja caja3 D)
	(persona-necesita-contenido persona5 medicine)
	(loc-persona persona5 T)
	(caja-contenido caja4 medicine)
	(loc-caja caja4 D)
	(persona-necesita-contenido persona6 food)
	(loc-persona persona6 I)
	(caja-contenido caja5 food)
	(loc-caja caja5 U)
	(persona-necesita-contenido persona7 food)
	(loc-persona persona7 V)
	(caja-contenido caja6 food)
	(loc-caja caja6 U)
	(persona-necesita-contenido persona8 food)
	(loc-persona persona8 A)
	(caja-contenido caja7 food)
	(loc-caja caja7 H)
	(persona-necesita-contenido persona8 medicine)
	(loc-persona persona8 B)
	(caja-contenido caja8 medicine)
	(loc-caja caja8 T)
	(persona-necesita-contenido persona9 food)
	(loc-persona persona9 E)
	(caja-contenido caja9 food)
	(loc-caja caja9 N)
	(persona-necesita-contenido persona9 medicine)
	(loc-persona persona9 D)
	(caja-contenido caja10 medicine)
	(loc-caja caja10 S)
	(persona-necesita-contenido persona11 medicine)
	(loc-persona persona11 K)
	(caja-contenido caja11 medicine)
	(loc-caja caja11 R)
	(persona-necesita-contenido persona12 food)
	(loc-persona persona12 V)
	(caja-contenido caja12 food)
	(loc-caja caja12 R)
	(persona-necesita-contenido persona12 medicine)
	(loc-persona persona12 A)
	(caja-contenido caja13 medicine)
	(loc-caja caja13 A)
	(persona-necesita-contenido persona13 medicine)
	(loc-persona persona13 K)
	(caja-contenido caja14 medicine)
	(loc-caja caja14 K)
	(persona-necesita-contenido persona14 food)
	(loc-persona persona14 T)
	(caja-contenido caja15 food)
	(loc-caja caja15 D)
	(persona-necesita-contenido persona15 food)
	(loc-persona persona15 V)
	(caja-contenido caja16 food)
	(loc-caja caja16 J)
	(persona-necesita-contenido persona15 medicine)
	(loc-persona persona15 P)
	(caja-contenido caja17 medicine)
	(loc-caja caja17 P)
	(persona-necesita-contenido persona16 medicine)
	(loc-persona persona16 D)
	(caja-contenido caja18 medicine)
	(loc-caja caja18 Q)
	(persona-necesita-contenido persona19 food)
	(loc-persona persona19 V)
	(caja-contenido caja19 food)
	(loc-caja caja19 K)
	(persona-necesita-contenido persona20 medicine)
	(loc-persona persona20 O)
	(caja-contenido caja20 medicine)
	(loc-caja caja20 A)
	(persona-necesita-contenido persona21 food)
	(loc-persona persona21 J)
	(caja-contenido caja21 food)
	(loc-caja caja21 R)
	(persona-necesita-contenido persona21 medicine)
	(loc-persona persona21 C)
	(caja-contenido caja22 medicine)
	(loc-caja caja22 F)
	(brazo-dron-free dron1 brazo1)
	(brazo-dron-free dron1 brazo2)
)
(:goal (and

	(loc-dron dron1 deposito)
	(persona-tiene-contenido persona2 food)
	(persona-tiene-contenido persona3 medicine)
	(persona-tiene-contenido persona5 food)
	(persona-tiene-contenido persona5 medicine)
	(persona-tiene-contenido persona6 food)
	(persona-tiene-contenido persona7 food)
	(persona-tiene-contenido persona8 food)
	(persona-tiene-contenido persona8 medicine)
	(persona-tiene-contenido persona9 food)
	(persona-tiene-contenido persona9 medicine)
	(persona-tiene-contenido persona11 medicine)
	(persona-tiene-contenido persona12 food)
	(persona-tiene-contenido persona12 medicine)
	(persona-tiene-contenido persona13 medicine)
	(persona-tiene-contenido persona14 food)
	(persona-tiene-contenido persona15 food)
	(persona-tiene-contenido persona15 medicine)
	(persona-tiene-contenido persona16 medicine)
	(persona-tiene-contenido persona19 food)
	(persona-tiene-contenido persona20 medicine)
	(persona-tiene-contenido persona21 food)
	(persona-tiene-contenido persona21 medicine)
	))
)
