(define (problem drone_problem_d1_r0_l18_p18_c18_g18_ct2)(:domain logisticaSE)
(:objects
	dron1 - dron
	deposito - loc
	A - loc
	B - loc
	C - loc
	D - loc
	E - loc
	F - loc
	G - loc
	H - loc
	I - loc
	J - loc
	K - loc
	L - loc
	M - loc
	N - loc
	O - loc
	P - loc
	Q - loc
	R - loc
	caja1 - caja
	caja2 - caja
	caja3 - caja
	caja4 - caja
	caja5 - caja
	caja6 - caja
	caja7 - caja
	caja8 - caja
	caja9 - caja
	caja10 - caja
	caja11 - caja
	caja12 - caja
	caja13 - caja
	caja14 - caja
	caja15 - caja
	caja16 - caja
	caja17 - caja
	caja18 - caja
	food - contenido
	medicine - contenido
	persona0 - persona
	persona1 - persona
	persona2 - persona
	persona3 - persona
	persona4 - persona
	persona5 - persona
	persona6 - persona
	persona7 - persona
	persona8 - persona
	persona9 - persona
	persona10 - persona
	persona11 - persona
	persona12 - persona
	persona13 - persona
	persona14 - persona
	persona15 - persona
	persona16 - persona
	persona17 - persona
	brazo1 - brazo
	brazo2 - brazo)
(:init
	(loc-dron dron1 C)
	(persona-necesita-contenido persona0 food)
	(loc-persona persona0 R)
	(caja-contenido caja1 food)
	(loc-caja caja1 F)
	(persona-necesita-contenido persona0 medicine)
	(loc-persona persona0 K)
	(caja-contenido caja2 medicine)
	(loc-caja caja2 C)
	(persona-necesita-contenido persona1 medicine)
	(loc-persona persona1 K)
	(caja-contenido caja3 medicine)
	(loc-caja caja3 P)
	(persona-necesita-contenido persona2 medicine)
	(loc-persona persona2 K)
	(caja-contenido caja4 medicine)
	(loc-caja caja4 J)
	(persona-necesita-contenido persona3 medicine)
	(loc-persona persona3 G)
	(caja-contenido caja5 medicine)
	(loc-caja caja5 A)
	(persona-necesita-contenido persona4 medicine)
	(loc-persona persona4 K)
	(caja-contenido caja6 medicine)
	(loc-caja caja6 B)
	(persona-necesita-contenido persona5 medicine)
	(loc-persona persona5 F)
	(caja-contenido caja7 medicine)
	(loc-caja caja7 N)
	(persona-necesita-contenido persona6 medicine)
	(loc-persona persona6 P)
	(caja-contenido caja8 medicine)
	(loc-caja caja8 M)
	(persona-necesita-contenido persona7 medicine)
	(loc-persona persona7 F)
	(caja-contenido caja9 medicine)
	(loc-caja caja9 J)
	(persona-necesita-contenido persona8 medicine)
	(loc-persona persona8 I)
	(caja-contenido caja10 medicine)
	(loc-caja caja10 F)
	(persona-necesita-contenido persona10 medicine)
	(loc-persona persona10 J)
	(caja-contenido caja11 medicine)
	(loc-caja caja11 L)
	(persona-necesita-contenido persona11 food)
	(loc-persona persona11 M)
	(caja-contenido caja12 food)
	(loc-caja caja12 C)
	(persona-necesita-contenido persona11 medicine)
	(loc-persona persona11 G)
	(caja-contenido caja13 medicine)
	(loc-caja caja13 C)
	(persona-necesita-contenido persona12 medicine)
	(loc-persona persona12 O)
	(caja-contenido caja14 medicine)
	(loc-caja caja14 I)
	(persona-necesita-contenido persona13 medicine)
	(loc-persona persona13 F)
	(caja-contenido caja15 medicine)
	(loc-caja caja15 B)
	(persona-necesita-contenido persona14 food)
	(loc-persona persona14 B)
	(caja-contenido caja16 food)
	(loc-caja caja16 deposito)
	(persona-necesita-contenido persona15 medicine)
	(loc-persona persona15 G)
	(caja-contenido caja17 medicine)
	(loc-caja caja17 F)
	(persona-necesita-contenido persona16 medicine)
	(loc-persona persona16 J)
	(caja-contenido caja18 medicine)
	(loc-caja caja18 N)
	(brazo-dron-free dron1 brazo1)
	(brazo-dron-free dron1 brazo2)
)
(:goal (and

	(loc-dron dron1 deposito)
	(persona-tiene-contenido persona0 food)
	(persona-tiene-contenido persona0 medicine)
	(persona-tiene-contenido persona1 medicine)
	(persona-tiene-contenido persona2 medicine)
	(persona-tiene-contenido persona3 medicine)
	(persona-tiene-contenido persona4 medicine)
	(persona-tiene-contenido persona5 medicine)
	(persona-tiene-contenido persona6 medicine)
	(persona-tiene-contenido persona7 medicine)
	(persona-tiene-contenido persona8 medicine)
	(persona-tiene-contenido persona10 medicine)
	(persona-tiene-contenido persona11 food)
	(persona-tiene-contenido persona11 medicine)
	(persona-tiene-contenido persona12 medicine)
	(persona-tiene-contenido persona13 medicine)
	(persona-tiene-contenido persona14 food)
	(persona-tiene-contenido persona15 medicine)
	(persona-tiene-contenido persona16 medicine)
	))
)
