(define (problem drone_problem_d1_r0_l52_p52_c52_g52_ct2)(:domain logisticaSE)
(:objects
	dron1 - dron
	deposito - loc
	A - loc
	B - loc
	C - loc
	D - loc
	E - loc
	F - loc
	G - loc
	H - loc
	I - loc
	J - loc
	K - loc
	L - loc
	M - loc
	N - loc
	O - loc
	P - loc
	Q - loc
	R - loc
	S - loc
	T - loc
	U - loc
	V - loc
	W - loc
	X - loc
	Y - loc
	Z - loc
	A0 - loc
	B0 - loc
	C0 - loc
	D0 - loc
	E0 - loc
	F0 - loc
	G0 - loc
	H0 - loc
	I0 - loc
	J0 - loc
	K0 - loc
	L0 - loc
	M0 - loc
	N0 - loc
	O0 - loc
	P0 - loc
	Q0 - loc
	R0 - loc
	S0 - loc
	T0 - loc
	U0 - loc
	V0 - loc
	W0 - loc
	X0 - loc
	Y0 - loc
	Z0 - loc
	caja1 - caja
	caja2 - caja
	caja3 - caja
	caja4 - caja
	caja5 - caja
	caja6 - caja
	caja7 - caja
	caja8 - caja
	caja9 - caja
	caja10 - caja
	caja11 - caja
	caja12 - caja
	caja13 - caja
	caja14 - caja
	caja15 - caja
	caja16 - caja
	caja17 - caja
	caja18 - caja
	caja19 - caja
	caja20 - caja
	caja21 - caja
	caja22 - caja
	caja23 - caja
	caja24 - caja
	caja25 - caja
	caja26 - caja
	caja27 - caja
	caja28 - caja
	caja29 - caja
	caja30 - caja
	caja31 - caja
	caja32 - caja
	caja33 - caja
	caja34 - caja
	caja35 - caja
	caja36 - caja
	caja37 - caja
	caja38 - caja
	caja39 - caja
	caja40 - caja
	caja41 - caja
	caja42 - caja
	caja43 - caja
	caja44 - caja
	caja45 - caja
	caja46 - caja
	caja47 - caja
	caja48 - caja
	caja49 - caja
	caja50 - caja
	caja51 - caja
	caja52 - caja
	food - contenido
	medicine - contenido
	persona0 - persona
	persona1 - persona
	persona2 - persona
	persona3 - persona
	persona4 - persona
	persona5 - persona
	persona6 - persona
	persona7 - persona
	persona8 - persona
	persona9 - persona
	persona10 - persona
	persona11 - persona
	persona12 - persona
	persona13 - persona
	persona14 - persona
	persona15 - persona
	persona16 - persona
	persona17 - persona
	persona18 - persona
	persona19 - persona
	persona20 - persona
	persona21 - persona
	persona22 - persona
	persona23 - persona
	persona24 - persona
	persona25 - persona
	persona26 - persona
	persona27 - persona
	persona28 - persona
	persona29 - persona
	persona30 - persona
	persona31 - persona
	persona32 - persona
	persona33 - persona
	persona34 - persona
	persona35 - persona
	persona36 - persona
	persona37 - persona
	persona38 - persona
	persona39 - persona
	persona40 - persona
	persona41 - persona
	persona42 - persona
	persona43 - persona
	persona44 - persona
	persona45 - persona
	persona46 - persona
	persona47 - persona
	persona48 - persona
	persona49 - persona
	persona50 - persona
	persona51 - persona
	brazo1 - brazo
	brazo2 - brazo)
(:init
	(loc-dron dron1 O)
	(persona-necesita-contenido persona2 medicine)
	(loc-persona persona2 J)
	(caja-contenido caja1 medicine)
	(loc-caja caja1 A)
	(persona-necesita-contenido persona4 medicine)
	(loc-persona persona4 R0)
	(caja-contenido caja2 medicine)
	(loc-caja caja2 H)
	(persona-necesita-contenido persona6 medicine)
	(loc-persona persona6 Z)
	(caja-contenido caja3 medicine)
	(loc-caja caja3 U)
	(persona-necesita-contenido persona7 medicine)
	(loc-persona persona7 S0)
	(caja-contenido caja4 medicine)
	(loc-caja caja4 K0)
	(persona-necesita-contenido persona8 medicine)
	(loc-persona persona8 S0)
	(caja-contenido caja5 medicine)
	(loc-caja caja5 Y0)
	(persona-necesita-contenido persona9 medicine)
	(loc-persona persona9 R)
	(caja-contenido caja6 medicine)
	(loc-caja caja6 Y0)
	(persona-necesita-contenido persona10 medicine)
	(loc-persona persona10 E0)
	(caja-contenido caja7 medicine)
	(loc-caja caja7 A0)
	(persona-necesita-contenido persona11 medicine)
	(loc-persona persona11 I)
	(caja-contenido caja8 medicine)
	(loc-caja caja8 C)
	(persona-necesita-contenido persona12 food)
	(loc-persona persona12 W)
	(caja-contenido caja9 food)
	(loc-caja caja9 T0)
	(persona-necesita-contenido persona13 medicine)
	(loc-persona persona13 Y0)
	(caja-contenido caja10 medicine)
	(loc-caja caja10 E0)
	(persona-necesita-contenido persona16 food)
	(loc-persona persona16 B0)
	(caja-contenido caja11 food)
	(loc-caja caja11 W)
	(persona-necesita-contenido persona16 medicine)
	(loc-persona persona16 M0)
	(caja-contenido caja12 medicine)
	(loc-caja caja12 E0)
	(persona-necesita-contenido persona17 medicine)
	(loc-persona persona17 Z)
	(caja-contenido caja13 medicine)
	(loc-caja caja13 W)
	(persona-necesita-contenido persona18 food)
	(loc-persona persona18 A0)
	(caja-contenido caja14 food)
	(loc-caja caja14 O0)
	(persona-necesita-contenido persona18 medicine)
	(loc-persona persona18 K)
	(caja-contenido caja15 medicine)
	(loc-caja caja15 U)
	(persona-necesita-contenido persona19 medicine)
	(loc-persona persona19 Z0)
	(caja-contenido caja16 medicine)
	(loc-caja caja16 H)
	(persona-necesita-contenido persona20 food)
	(loc-persona persona20 T)
	(caja-contenido caja17 food)
	(loc-caja caja17 V)
	(persona-necesita-contenido persona20 medicine)
	(loc-persona persona20 G0)
	(caja-contenido caja18 medicine)
	(loc-caja caja18 M0)
	(persona-necesita-contenido persona21 medicine)
	(loc-persona persona21 Q)
	(caja-contenido caja19 medicine)
	(loc-caja caja19 X)
	(persona-necesita-contenido persona22 food)
	(loc-persona persona22 P0)
	(caja-contenido caja20 food)
	(loc-caja caja20 Z)
	(persona-necesita-contenido persona22 medicine)
	(loc-persona persona22 P0)
	(caja-contenido caja21 medicine)
	(loc-caja caja21 C)
	(persona-necesita-contenido persona23 medicine)
	(loc-persona persona23 H)
	(caja-contenido caja22 medicine)
	(loc-caja caja22 P0)
	(persona-necesita-contenido persona24 medicine)
	(loc-persona persona24 X0)
	(caja-contenido caja23 medicine)
	(loc-caja caja23 X)
	(persona-necesita-contenido persona25 medicine)
	(loc-persona persona25 D)
	(caja-contenido caja24 medicine)
	(loc-caja caja24 M0)
	(persona-necesita-contenido persona26 food)
	(loc-persona persona26 G0)
	(caja-contenido caja25 food)
	(loc-caja caja25 G0)
	(persona-necesita-contenido persona26 medicine)
	(loc-persona persona26 A0)
	(caja-contenido caja26 medicine)
	(loc-caja caja26 I)
	(persona-necesita-contenido persona28 food)
	(loc-persona persona28 Y)
	(caja-contenido caja27 food)
	(loc-caja caja27 W)
	(persona-necesita-contenido persona28 medicine)
	(loc-persona persona28 X)
	(caja-contenido caja28 medicine)
	(loc-caja caja28 P)
	(persona-necesita-contenido persona29 medicine)
	(loc-persona persona29 H0)
	(caja-contenido caja29 medicine)
	(loc-caja caja29 H0)
	(persona-necesita-contenido persona30 medicine)
	(loc-persona persona30 Z)
	(caja-contenido caja30 medicine)
	(loc-caja caja30 U0)
	(persona-necesita-contenido persona32 medicine)
	(loc-persona persona32 X)
	(caja-contenido caja31 medicine)
	(loc-caja caja31 V0)
	(persona-necesita-contenido persona33 food)
	(loc-persona persona33 O)
	(caja-contenido caja32 food)
	(loc-caja caja32 L)
	(persona-necesita-contenido persona33 medicine)
	(loc-persona persona33 D)
	(caja-contenido caja33 medicine)
	(loc-caja caja33 R0)
	(persona-necesita-contenido persona34 food)
	(loc-persona persona34 F0)
	(caja-contenido caja34 food)
	(loc-caja caja34 Y0)
	(persona-necesita-contenido persona34 medicine)
	(loc-persona persona34 L0)
	(caja-contenido caja35 medicine)
	(loc-caja caja35 U)
	(persona-necesita-contenido persona35 medicine)
	(loc-persona persona35 K0)
	(caja-contenido caja36 medicine)
	(loc-caja caja36 N0)
	(persona-necesita-contenido persona36 medicine)
	(loc-persona persona36 P0)
	(caja-contenido caja37 medicine)
	(loc-caja caja37 C0)
	(persona-necesita-contenido persona37 food)
	(loc-persona persona37 U0)
	(caja-contenido caja38 food)
	(loc-caja caja38 J0)
	(persona-necesita-contenido persona37 medicine)
	(loc-persona persona37 E)
	(caja-contenido caja39 medicine)
	(loc-caja caja39 K0)
	(persona-necesita-contenido persona38 medicine)
	(loc-persona persona38 J0)
	(caja-contenido caja40 medicine)
	(loc-caja caja40 Y0)
	(persona-necesita-contenido persona39 food)
	(loc-persona persona39 N)
	(caja-contenido caja41 food)
	(loc-caja caja41 Q0)
	(persona-necesita-contenido persona39 medicine)
	(loc-persona persona39 Q0)
	(caja-contenido caja42 medicine)
	(loc-caja caja42 V)
	(persona-necesita-contenido persona40 medicine)
	(loc-persona persona40 P)
	(caja-contenido caja43 medicine)
	(loc-caja caja43 V)
	(persona-necesita-contenido persona41 medicine)
	(loc-persona persona41 T)
	(caja-contenido caja44 medicine)
	(loc-caja caja44 H0)
	(persona-necesita-contenido persona42 medicine)
	(loc-persona persona42 S)
	(caja-contenido caja45 medicine)
	(loc-caja caja45 R)
	(persona-necesita-contenido persona43 food)
	(loc-persona persona43 I0)
	(caja-contenido caja46 food)
	(loc-caja caja46 U)
	(persona-necesita-contenido persona44 medicine)
	(loc-persona persona44 H0)
	(caja-contenido caja47 medicine)
	(loc-caja caja47 N)
	(persona-necesita-contenido persona46 medicine)
	(loc-persona persona46 I0)
	(caja-contenido caja48 medicine)
	(loc-caja caja48 I)
	(persona-necesita-contenido persona47 medicine)
	(loc-persona persona47 U0)
	(caja-contenido caja49 medicine)
	(loc-caja caja49 V0)
	(persona-necesita-contenido persona48 medicine)
	(loc-persona persona48 Z0)
	(caja-contenido caja50 medicine)
	(loc-caja caja50 deposito)
	(persona-necesita-contenido persona50 medicine)
	(loc-persona persona50 X)
	(caja-contenido caja51 medicine)
	(loc-caja caja51 A)
	(persona-necesita-contenido persona51 medicine)
	(loc-persona persona51 V0)
	(caja-contenido caja52 medicine)
	(loc-caja caja52 D0)
	(brazo-dron-free dron1 brazo1)
	(brazo-dron-free dron1 brazo2)
)
(:goal (and

	(loc-dron dron1 deposito)
	(persona-tiene-contenido persona2 medicine)
	(persona-tiene-contenido persona4 medicine)
	(persona-tiene-contenido persona6 medicine)
	(persona-tiene-contenido persona7 medicine)
	(persona-tiene-contenido persona8 medicine)
	(persona-tiene-contenido persona9 medicine)
	(persona-tiene-contenido persona10 medicine)
	(persona-tiene-contenido persona11 medicine)
	(persona-tiene-contenido persona12 food)
	(persona-tiene-contenido persona13 medicine)
	(persona-tiene-contenido persona16 food)
	(persona-tiene-contenido persona16 medicine)
	(persona-tiene-contenido persona17 medicine)
	(persona-tiene-contenido persona18 food)
	(persona-tiene-contenido persona18 medicine)
	(persona-tiene-contenido persona19 medicine)
	(persona-tiene-contenido persona20 food)
	(persona-tiene-contenido persona20 medicine)
	(persona-tiene-contenido persona21 medicine)
	(persona-tiene-contenido persona22 food)
	(persona-tiene-contenido persona22 medicine)
	(persona-tiene-contenido persona23 medicine)
	(persona-tiene-contenido persona24 medicine)
	(persona-tiene-contenido persona25 medicine)
	(persona-tiene-contenido persona26 food)
	(persona-tiene-contenido persona26 medicine)
	(persona-tiene-contenido persona28 food)
	(persona-tiene-contenido persona28 medicine)
	(persona-tiene-contenido persona29 medicine)
	(persona-tiene-contenido persona30 medicine)
	(persona-tiene-contenido persona32 medicine)
	(persona-tiene-contenido persona33 food)
	(persona-tiene-contenido persona33 medicine)
	(persona-tiene-contenido persona34 food)
	(persona-tiene-contenido persona34 medicine)
	(persona-tiene-contenido persona35 medicine)
	(persona-tiene-contenido persona36 medicine)
	(persona-tiene-contenido persona37 food)
	(persona-tiene-contenido persona37 medicine)
	(persona-tiene-contenido persona38 medicine)
	(persona-tiene-contenido persona39 food)
	(persona-tiene-contenido persona39 medicine)
	(persona-tiene-contenido persona40 medicine)
	(persona-tiene-contenido persona41 medicine)
	(persona-tiene-contenido persona42 medicine)
	(persona-tiene-contenido persona43 food)
	(persona-tiene-contenido persona44 medicine)
	(persona-tiene-contenido persona46 medicine)
	(persona-tiene-contenido persona47 medicine)
	(persona-tiene-contenido persona48 medicine)
	(persona-tiene-contenido persona50 medicine)
	(persona-tiene-contenido persona51 medicine)
	))
)
