(define (problem drone_problem_d1_r0_l14_p14_c14_g14_ct2)(:domain logisticaSE)
(:objects
	dron1 - dron
	deposito - loc
	A - loc
	B - loc
	C - loc
	D - loc
	E - loc
	F - loc
	G - loc
	H - loc
	I - loc
	J - loc
	K - loc
	L - loc
	M - loc
	N - loc
	caja1 - caja
	caja2 - caja
	caja3 - caja
	caja4 - caja
	caja5 - caja
	caja6 - caja
	caja7 - caja
	caja8 - caja
	caja9 - caja
	caja10 - caja
	caja11 - caja
	caja12 - caja
	caja13 - caja
	caja14 - caja
	food - contenido
	medicine - contenido
	persona0 - persona
	persona1 - persona
	persona2 - persona
	persona3 - persona
	persona4 - persona
	persona5 - persona
	persona6 - persona
	persona7 - persona
	persona8 - persona
	persona9 - persona
	persona10 - persona
	persona11 - persona
	persona12 - persona
	persona13 - persona
	brazo1 - brazo
	brazo2 - brazo)
(:init
	(loc-dron dron1 E)
	(persona-necesita-contenido persona0 food)
	(loc-persona persona0 H)
	(caja-contenido caja1 food)
	(loc-caja caja1 C)
	(persona-necesita-contenido persona2 food)
	(loc-persona persona2 N)
	(caja-contenido caja2 food)
	(loc-caja caja2 M)
	(persona-necesita-contenido persona2 medicine)
	(loc-persona persona2 F)
	(caja-contenido caja3 medicine)
	(loc-caja caja3 L)
	(persona-necesita-contenido persona3 food)
	(loc-persona persona3 M)
	(caja-contenido caja4 food)
	(loc-caja caja4 G)
	(persona-necesita-contenido persona4 food)
	(loc-persona persona4 N)
	(caja-contenido caja5 food)
	(loc-caja caja5 J)
	(persona-necesita-contenido persona6 food)
	(loc-persona persona6 deposito)
	(caja-contenido caja6 food)
	(loc-caja caja6 G)
	(persona-necesita-contenido persona7 food)
	(loc-persona persona7 L)
	(caja-contenido caja7 food)
	(loc-caja caja7 G)
	(persona-necesita-contenido persona8 food)
	(loc-persona persona8 E)
	(caja-contenido caja8 food)
	(loc-caja caja8 F)
	(persona-necesita-contenido persona9 food)
	(loc-persona persona9 C)
	(caja-contenido caja9 food)
	(loc-caja caja9 K)
	(persona-necesita-contenido persona10 food)
	(loc-persona persona10 A)
	(caja-contenido caja10 food)
	(loc-caja caja10 E)
	(persona-necesita-contenido persona11 food)
	(loc-persona persona11 deposito)
	(caja-contenido caja11 food)
	(loc-caja caja11 C)
	(persona-necesita-contenido persona12 food)
	(loc-persona persona12 I)
	(caja-contenido caja12 food)
	(loc-caja caja12 M)
	(persona-necesita-contenido persona13 food)
	(loc-persona persona13 F)
	(caja-contenido caja13 food)
	(loc-caja caja13 J)
	(persona-necesita-contenido persona13 medicine)
	(loc-persona persona13 K)
	(caja-contenido caja14 medicine)
	(loc-caja caja14 G)
	(brazo-dron-free dron1 brazo1)
	(brazo-dron-free dron1 brazo2)
)
(:goal (and

	(loc-dron dron1 deposito)
	(persona-tiene-contenido persona0 food)
	(persona-tiene-contenido persona2 food)
	(persona-tiene-contenido persona2 medicine)
	(persona-tiene-contenido persona3 food)
	(persona-tiene-contenido persona4 food)
	(persona-tiene-contenido persona6 food)
	(persona-tiene-contenido persona7 food)
	(persona-tiene-contenido persona8 food)
	(persona-tiene-contenido persona9 food)
	(persona-tiene-contenido persona10 food)
	(persona-tiene-contenido persona11 food)
	(persona-tiene-contenido persona12 food)
	(persona-tiene-contenido persona13 food)
	(persona-tiene-contenido persona13 medicine)
	))
)
