(define (problem drone_problem_d1_r0_l110_p110_c110_g110_ct2)(:domain logisticaSE)
(:objects
	dron1 - dron
	deposito - loc
	Loc1 - loc
	Loc2 - loc
	Loc3 - loc
	Loc4 - loc
	Loc5 - loc
	Loc6 - loc
	Loc7 - loc
	Loc8 - loc
	Loc9 - loc
	Loc10 - loc
	Loc11 - loc
	Loc12 - loc
	Loc13 - loc
	Loc14 - loc
	Loc15 - loc
	Loc16 - loc
	Loc17 - loc
	Loc18 - loc
	Loc19 - loc
	Loc20 - loc
	Loc21 - loc
	Loc22 - loc
	Loc23 - loc
	Loc24 - loc
	Loc25 - loc
	Loc26 - loc
	Loc27 - loc
	Loc28 - loc
	Loc29 - loc
	Loc30 - loc
	Loc31 - loc
	Loc32 - loc
	Loc33 - loc
	Loc34 - loc
	Loc35 - loc
	Loc36 - loc
	Loc37 - loc
	Loc38 - loc
	Loc39 - loc
	Loc40 - loc
	Loc41 - loc
	Loc42 - loc
	Loc43 - loc
	Loc44 - loc
	Loc45 - loc
	Loc46 - loc
	Loc47 - loc
	Loc48 - loc
	Loc49 - loc
	Loc50 - loc
	Loc51 - loc
	Loc52 - loc
	Loc53 - loc
	Loc54 - loc
	Loc55 - loc
	Loc56 - loc
	Loc57 - loc
	Loc58 - loc
	Loc59 - loc
	Loc60 - loc
	Loc61 - loc
	Loc62 - loc
	Loc63 - loc
	Loc64 - loc
	Loc65 - loc
	Loc66 - loc
	Loc67 - loc
	Loc68 - loc
	Loc69 - loc
	Loc70 - loc
	Loc71 - loc
	Loc72 - loc
	Loc73 - loc
	Loc74 - loc
	Loc75 - loc
	Loc76 - loc
	Loc77 - loc
	Loc78 - loc
	Loc79 - loc
	Loc80 - loc
	Loc81 - loc
	Loc82 - loc
	Loc83 - loc
	Loc84 - loc
	Loc85 - loc
	Loc86 - loc
	Loc87 - loc
	Loc88 - loc
	Loc89 - loc
	Loc90 - loc
	Loc91 - loc
	Loc92 - loc
	Loc93 - loc
	Loc94 - loc
	Loc95 - loc
	Loc96 - loc
	Loc97 - loc
	Loc98 - loc
	Loc99 - loc
	Loc100 - loc
	Loc101 - loc
	Loc102 - loc
	Loc103 - loc
	Loc104 - loc
	Loc105 - loc
	Loc106 - loc
	Loc107 - loc
	Loc108 - loc
	Loc109 - loc
	Loc110 - loc
	caja1 - caja
	caja2 - caja
	caja3 - caja
	caja4 - caja
	caja5 - caja
	caja6 - caja
	caja7 - caja
	caja8 - caja
	caja9 - caja
	caja10 - caja
	caja11 - caja
	caja12 - caja
	caja13 - caja
	caja14 - caja
	caja15 - caja
	caja16 - caja
	caja17 - caja
	caja18 - caja
	caja19 - caja
	caja20 - caja
	caja21 - caja
	caja22 - caja
	caja23 - caja
	caja24 - caja
	caja25 - caja
	caja26 - caja
	caja27 - caja
	caja28 - caja
	caja29 - caja
	caja30 - caja
	caja31 - caja
	caja32 - caja
	caja33 - caja
	caja34 - caja
	caja35 - caja
	caja36 - caja
	caja37 - caja
	caja38 - caja
	caja39 - caja
	caja40 - caja
	caja41 - caja
	caja42 - caja
	caja43 - caja
	caja44 - caja
	caja45 - caja
	caja46 - caja
	caja47 - caja
	caja48 - caja
	caja49 - caja
	caja50 - caja
	caja51 - caja
	caja52 - caja
	caja53 - caja
	caja54 - caja
	caja55 - caja
	caja56 - caja
	caja57 - caja
	caja58 - caja
	caja59 - caja
	caja60 - caja
	caja61 - caja
	caja62 - caja
	caja63 - caja
	caja64 - caja
	caja65 - caja
	caja66 - caja
	caja67 - caja
	caja68 - caja
	caja69 - caja
	caja70 - caja
	caja71 - caja
	caja72 - caja
	caja73 - caja
	caja74 - caja
	caja75 - caja
	caja76 - caja
	caja77 - caja
	caja78 - caja
	caja79 - caja
	caja80 - caja
	caja81 - caja
	caja82 - caja
	caja83 - caja
	caja84 - caja
	caja85 - caja
	caja86 - caja
	caja87 - caja
	caja88 - caja
	caja89 - caja
	caja90 - caja
	caja91 - caja
	caja92 - caja
	caja93 - caja
	caja94 - caja
	caja95 - caja
	caja96 - caja
	caja97 - caja
	caja98 - caja
	caja99 - caja
	caja100 - caja
	caja101 - caja
	caja102 - caja
	caja103 - caja
	caja104 - caja
	caja105 - caja
	caja106 - caja
	caja107 - caja
	caja108 - caja
	caja109 - caja
	caja110 - caja
	food - contenido
	medicine - contenido
	persona0 - persona
	persona1 - persona
	persona2 - persona
	persona3 - persona
	persona4 - persona
	persona5 - persona
	persona6 - persona
	persona7 - persona
	persona8 - persona
	persona9 - persona
	persona10 - persona
	persona11 - persona
	persona12 - persona
	persona13 - persona
	persona14 - persona
	persona15 - persona
	persona16 - persona
	persona17 - persona
	persona18 - persona
	persona19 - persona
	persona20 - persona
	persona21 - persona
	persona22 - persona
	persona23 - persona
	persona24 - persona
	persona25 - persona
	persona26 - persona
	persona27 - persona
	persona28 - persona
	persona29 - persona
	persona30 - persona
	persona31 - persona
	persona32 - persona
	persona33 - persona
	persona34 - persona
	persona35 - persona
	persona36 - persona
	persona37 - persona
	persona38 - persona
	persona39 - persona
	persona40 - persona
	persona41 - persona
	persona42 - persona
	persona43 - persona
	persona44 - persona
	persona45 - persona
	persona46 - persona
	persona47 - persona
	persona48 - persona
	persona49 - persona
	persona50 - persona
	persona51 - persona
	persona52 - persona
	persona53 - persona
	persona54 - persona
	persona55 - persona
	persona56 - persona
	persona57 - persona
	persona58 - persona
	persona59 - persona
	persona60 - persona
	persona61 - persona
	persona62 - persona
	persona63 - persona
	persona64 - persona
	persona65 - persona
	persona66 - persona
	persona67 - persona
	persona68 - persona
	persona69 - persona
	persona70 - persona
	persona71 - persona
	persona72 - persona
	persona73 - persona
	persona74 - persona
	persona75 - persona
	persona76 - persona
	persona77 - persona
	persona78 - persona
	persona79 - persona
	persona80 - persona
	persona81 - persona
	persona82 - persona
	persona83 - persona
	persona84 - persona
	persona85 - persona
	persona86 - persona
	persona87 - persona
	persona88 - persona
	persona89 - persona
	persona90 - persona
	persona91 - persona
	persona92 - persona
	persona93 - persona
	persona94 - persona
	persona95 - persona
	persona96 - persona
	persona97 - persona
	persona98 - persona
	persona99 - persona
	persona100 - persona
	persona101 - persona
	persona102 - persona
	persona103 - persona
	persona104 - persona
	persona105 - persona
	persona106 - persona
	persona107 - persona
	persona108 - persona
	persona109 - persona
	brazo1 - brazo
	brazo2 - brazo)
(:init
	(loc-dron dron1 Loc38)
	(persona-necesita-contenido persona0 food)
	(loc-persona persona0 Loc107)
	(caja-contenido caja1 food)
	(loc-caja caja1 deposito)
	(persona-necesita-contenido persona1 food)
	(loc-persona persona1 Loc107)
	(caja-contenido caja2 food)
	(loc-caja caja2 deposito)
	(persona-necesita-contenido persona2 food)
	(loc-persona persona2 Loc46)
	(caja-contenido caja3 food)
	(loc-caja caja3 deposito)
	(persona-necesita-contenido persona3 food)
	(loc-persona persona3 Loc103)
	(caja-contenido caja4 food)
	(loc-caja caja4 deposito)
	(persona-necesita-contenido persona4 food)
	(loc-persona persona4 Loc19)
	(caja-contenido caja5 food)
	(loc-caja caja5 deposito)
	(persona-necesita-contenido persona5 food)
	(loc-persona persona5 Loc22)
	(caja-contenido caja6 food)
	(loc-caja caja6 deposito)
	(persona-necesita-contenido persona6 food)
	(loc-persona persona6 Loc103)
	(caja-contenido caja7 food)
	(loc-caja caja7 deposito)
	(persona-necesita-contenido persona7 food)
	(loc-persona persona7 Loc110)
	(caja-contenido caja8 food)
	(loc-caja caja8 deposito)
	(persona-necesita-contenido persona8 food)
	(loc-persona persona8 Loc55)
	(caja-contenido caja9 food)
	(loc-caja caja9 deposito)
	(persona-necesita-contenido persona9 food)
	(loc-persona persona9 Loc55)
	(caja-contenido caja10 food)
	(loc-caja caja10 deposito)
	(persona-necesita-contenido persona10 food)
	(loc-persona persona10 Loc59)
	(caja-contenido caja11 food)
	(loc-caja caja11 deposito)
	(persona-necesita-contenido persona12 food)
	(loc-persona persona12 Loc16)
	(caja-contenido caja12 food)
	(loc-caja caja12 deposito)
	(persona-necesita-contenido persona13 food)
	(loc-persona persona13 Loc90)
	(caja-contenido caja13 food)
	(loc-caja caja13 deposito)
	(persona-necesita-contenido persona14 food)
	(loc-persona persona14 Loc70)
	(caja-contenido caja14 food)
	(loc-caja caja14 deposito)
	(persona-necesita-contenido persona15 food)
	(loc-persona persona15 Loc3)
	(caja-contenido caja15 food)
	(loc-caja caja15 deposito)
	(persona-necesita-contenido persona16 food)
	(loc-persona persona16 Loc55)
	(caja-contenido caja16 food)
	(loc-caja caja16 deposito)
	(persona-necesita-contenido persona17 food)
	(loc-persona persona17 Loc19)
	(caja-contenido caja17 food)
	(loc-caja caja17 deposito)
	(persona-necesita-contenido persona18 food)
	(loc-persona persona18 Loc68)
	(caja-contenido caja18 food)
	(loc-caja caja18 deposito)
	(persona-necesita-contenido persona19 food)
	(loc-persona persona19 Loc90)
	(caja-contenido caja19 food)
	(loc-caja caja19 deposito)
	(persona-necesita-contenido persona19 medicine)
	(loc-persona persona19 Loc43)
	(caja-contenido caja20 medicine)
	(loc-caja caja20 deposito)
	(persona-necesita-contenido persona20 food)
	(loc-persona persona20 Loc34)
	(caja-contenido caja21 food)
	(loc-caja caja21 deposito)
	(persona-necesita-contenido persona22 food)
	(loc-persona persona22 Loc67)
	(caja-contenido caja22 food)
	(loc-caja caja22 deposito)
	(persona-necesita-contenido persona23 food)
	(loc-persona persona23 Loc6)
	(caja-contenido caja23 food)
	(loc-caja caja23 deposito)
	(persona-necesita-contenido persona24 food)
	(loc-persona persona24 Loc44)
	(caja-contenido caja24 food)
	(loc-caja caja24 deposito)
	(persona-necesita-contenido persona25 food)
	(loc-persona persona25 Loc109)
	(caja-contenido caja25 food)
	(loc-caja caja25 deposito)
	(persona-necesita-contenido persona26 food)
	(loc-persona persona26 Loc50)
	(caja-contenido caja26 food)
	(loc-caja caja26 deposito)
	(persona-necesita-contenido persona27 food)
	(loc-persona persona27 Loc30)
	(caja-contenido caja27 food)
	(loc-caja caja27 deposito)
	(persona-necesita-contenido persona28 food)
	(loc-persona persona28 Loc31)
	(caja-contenido caja28 food)
	(loc-caja caja28 deposito)
	(persona-necesita-contenido persona29 food)
	(loc-persona persona29 Loc16)
	(caja-contenido caja29 food)
	(loc-caja caja29 deposito)
	(persona-necesita-contenido persona30 food)
	(loc-persona persona30 Loc20)
	(caja-contenido caja30 food)
	(loc-caja caja30 deposito)
	(persona-necesita-contenido persona31 food)
	(loc-persona persona31 Loc52)
	(caja-contenido caja31 food)
	(loc-caja caja31 deposito)
	(persona-necesita-contenido persona32 food)
	(loc-persona persona32 Loc25)
	(caja-contenido caja32 food)
	(loc-caja caja32 deposito)
	(persona-necesita-contenido persona33 food)
	(loc-persona persona33 Loc87)
	(caja-contenido caja33 food)
	(loc-caja caja33 deposito)
	(persona-necesita-contenido persona34 food)
	(loc-persona persona34 Loc64)
	(caja-contenido caja34 food)
	(loc-caja caja34 deposito)
	(persona-necesita-contenido persona34 medicine)
	(loc-persona persona34 Loc84)
	(caja-contenido caja35 medicine)
	(loc-caja caja35 deposito)
	(persona-necesita-contenido persona35 food)
	(loc-persona persona35 Loc5)
	(caja-contenido caja36 food)
	(loc-caja caja36 deposito)
	(persona-necesita-contenido persona36 food)
	(loc-persona persona36 Loc22)
	(caja-contenido caja37 food)
	(loc-caja caja37 deposito)
	(persona-necesita-contenido persona37 food)
	(loc-persona persona37 Loc67)
	(caja-contenido caja38 food)
	(loc-caja caja38 deposito)
	(persona-necesita-contenido persona38 food)
	(loc-persona persona38 Loc61)
	(caja-contenido caja39 food)
	(loc-caja caja39 deposito)
	(persona-necesita-contenido persona39 food)
	(loc-persona persona39 Loc18)
	(caja-contenido caja40 food)
	(loc-caja caja40 deposito)
	(persona-necesita-contenido persona40 food)
	(loc-persona persona40 Loc93)
	(caja-contenido caja41 food)
	(loc-caja caja41 deposito)
	(persona-necesita-contenido persona41 food)
	(loc-persona persona41 Loc77)
	(caja-contenido caja42 food)
	(loc-caja caja42 deposito)
	(persona-necesita-contenido persona42 food)
	(loc-persona persona42 Loc33)
	(caja-contenido caja43 food)
	(loc-caja caja43 deposito)
	(persona-necesita-contenido persona43 food)
	(loc-persona persona43 Loc32)
	(caja-contenido caja44 food)
	(loc-caja caja44 deposito)
	(persona-necesita-contenido persona44 food)
	(loc-persona persona44 Loc28)
	(caja-contenido caja45 food)
	(loc-caja caja45 deposito)
	(persona-necesita-contenido persona45 food)
	(loc-persona persona45 Loc10)
	(caja-contenido caja46 food)
	(loc-caja caja46 deposito)
	(persona-necesita-contenido persona46 food)
	(loc-persona persona46 Loc71)
	(caja-contenido caja47 food)
	(loc-caja caja47 deposito)
	(persona-necesita-contenido persona47 food)
	(loc-persona persona47 Loc89)
	(caja-contenido caja48 food)
	(loc-caja caja48 deposito)
	(persona-necesita-contenido persona48 food)
	(loc-persona persona48 Loc107)
	(caja-contenido caja49 food)
	(loc-caja caja49 deposito)
	(persona-necesita-contenido persona49 food)
	(loc-persona persona49 Loc63)
	(caja-contenido caja50 food)
	(loc-caja caja50 deposito)
	(persona-necesita-contenido persona50 food)
	(loc-persona persona50 Loc90)
	(caja-contenido caja51 food)
	(loc-caja caja51 deposito)
	(persona-necesita-contenido persona51 food)
	(loc-persona persona51 Loc21)
	(caja-contenido caja52 food)
	(loc-caja caja52 deposito)
	(persona-necesita-contenido persona52 food)
	(loc-persona persona52 Loc109)
	(caja-contenido caja53 food)
	(loc-caja caja53 deposito)
	(persona-necesita-contenido persona53 food)
	(loc-persona persona53 Loc32)
	(caja-contenido caja54 food)
	(loc-caja caja54 deposito)
	(persona-necesita-contenido persona54 food)
	(loc-persona persona54 Loc35)
	(caja-contenido caja55 food)
	(loc-caja caja55 deposito)
	(persona-necesita-contenido persona55 food)
	(loc-persona persona55 Loc86)
	(caja-contenido caja56 food)
	(loc-caja caja56 deposito)
	(persona-necesita-contenido persona56 food)
	(loc-persona persona56 Loc32)
	(caja-contenido caja57 food)
	(loc-caja caja57 deposito)
	(persona-necesita-contenido persona57 food)
	(loc-persona persona57 Loc77)
	(caja-contenido caja58 food)
	(loc-caja caja58 deposito)
	(persona-necesita-contenido persona58 food)
	(loc-persona persona58 Loc52)
	(caja-contenido caja59 food)
	(loc-caja caja59 deposito)
	(persona-necesita-contenido persona58 medicine)
	(loc-persona persona58 Loc18)
	(caja-contenido caja60 medicine)
	(loc-caja caja60 deposito)
	(persona-necesita-contenido persona59 food)
	(loc-persona persona59 Loc40)
	(caja-contenido caja61 food)
	(loc-caja caja61 deposito)
	(persona-necesita-contenido persona60 food)
	(loc-persona persona60 Loc39)
	(caja-contenido caja62 food)
	(loc-caja caja62 deposito)
	(persona-necesita-contenido persona61 food)
	(loc-persona persona61 Loc54)
	(caja-contenido caja63 food)
	(loc-caja caja63 deposito)
	(persona-necesita-contenido persona62 food)
	(loc-persona persona62 Loc33)
	(caja-contenido caja64 food)
	(loc-caja caja64 deposito)
	(persona-necesita-contenido persona63 food)
	(loc-persona persona63 Loc17)
	(caja-contenido caja65 food)
	(loc-caja caja65 deposito)
	(persona-necesita-contenido persona64 food)
	(loc-persona persona64 Loc54)
	(caja-contenido caja66 food)
	(loc-caja caja66 deposito)
	(persona-necesita-contenido persona65 food)
	(loc-persona persona65 Loc109)
	(caja-contenido caja67 food)
	(loc-caja caja67 deposito)
	(persona-necesita-contenido persona66 food)
	(loc-persona persona66 Loc71)
	(caja-contenido caja68 food)
	(loc-caja caja68 deposito)
	(persona-necesita-contenido persona67 food)
	(loc-persona persona67 Loc35)
	(caja-contenido caja69 food)
	(loc-caja caja69 deposito)
	(persona-necesita-contenido persona68 food)
	(loc-persona persona68 Loc34)
	(caja-contenido caja70 food)
	(loc-caja caja70 deposito)
	(persona-necesita-contenido persona69 food)
	(loc-persona persona69 Loc82)
	(caja-contenido caja71 food)
	(loc-caja caja71 deposito)
	(persona-necesita-contenido persona71 food)
	(loc-persona persona71 Loc15)
	(caja-contenido caja72 food)
	(loc-caja caja72 deposito)
	(persona-necesita-contenido persona72 food)
	(loc-persona persona72 Loc85)
	(caja-contenido caja73 food)
	(loc-caja caja73 deposito)
	(persona-necesita-contenido persona72 medicine)
	(loc-persona persona72 Loc61)
	(caja-contenido caja74 medicine)
	(loc-caja caja74 deposito)
	(persona-necesita-contenido persona73 food)
	(loc-persona persona73 Loc35)
	(caja-contenido caja75 food)
	(loc-caja caja75 deposito)
	(persona-necesita-contenido persona74 food)
	(loc-persona persona74 Loc15)
	(caja-contenido caja76 food)
	(loc-caja caja76 deposito)
	(persona-necesita-contenido persona75 food)
	(loc-persona persona75 Loc34)
	(caja-contenido caja77 food)
	(loc-caja caja77 deposito)
	(persona-necesita-contenido persona76 food)
	(loc-persona persona76 Loc10)
	(caja-contenido caja78 food)
	(loc-caja caja78 deposito)
	(persona-necesita-contenido persona77 food)
	(loc-persona persona77 Loc95)
	(caja-contenido caja79 food)
	(loc-caja caja79 deposito)
	(persona-necesita-contenido persona78 food)
	(loc-persona persona78 Loc103)
	(caja-contenido caja80 food)
	(loc-caja caja80 deposito)
	(persona-necesita-contenido persona79 food)
	(loc-persona persona79 Loc54)
	(caja-contenido caja81 food)
	(loc-caja caja81 deposito)
	(persona-necesita-contenido persona80 food)
	(loc-persona persona80 Loc10)
	(caja-contenido caja82 food)
	(loc-caja caja82 deposito)
	(persona-necesita-contenido persona81 food)
	(loc-persona persona81 Loc45)
	(caja-contenido caja83 food)
	(loc-caja caja83 deposito)
	(persona-necesita-contenido persona82 food)
	(loc-persona persona82 Loc7)
	(caja-contenido caja84 food)
	(loc-caja caja84 deposito)
	(persona-necesita-contenido persona83 food)
	(loc-persona persona83 Loc60)
	(caja-contenido caja85 food)
	(loc-caja caja85 deposito)
	(persona-necesita-contenido persona84 food)
	(loc-persona persona84 Loc99)
	(caja-contenido caja86 food)
	(loc-caja caja86 deposito)
	(persona-necesita-contenido persona85 food)
	(loc-persona persona85 Loc28)
	(caja-contenido caja87 food)
	(loc-caja caja87 deposito)
	(persona-necesita-contenido persona86 food)
	(loc-persona persona86 Loc58)
	(caja-contenido caja88 food)
	(loc-caja caja88 deposito)
	(persona-necesita-contenido persona87 food)
	(loc-persona persona87 Loc67)
	(caja-contenido caja89 food)
	(loc-caja caja89 deposito)
	(persona-necesita-contenido persona88 food)
	(loc-persona persona88 Loc19)
	(caja-contenido caja90 food)
	(loc-caja caja90 deposito)
	(persona-necesita-contenido persona89 food)
	(loc-persona persona89 Loc31)
	(caja-contenido caja91 food)
	(loc-caja caja91 deposito)
	(persona-necesita-contenido persona90 food)
	(loc-persona persona90 Loc47)
	(caja-contenido caja92 food)
	(loc-caja caja92 deposito)
	(persona-necesita-contenido persona91 food)
	(loc-persona persona91 Loc77)
	(caja-contenido caja93 food)
	(loc-caja caja93 deposito)
	(persona-necesita-contenido persona92 food)
	(loc-persona persona92 Loc97)
	(caja-contenido caja94 food)
	(loc-caja caja94 deposito)
	(persona-necesita-contenido persona93 food)
	(loc-persona persona93 Loc90)
	(caja-contenido caja95 food)
	(loc-caja caja95 deposito)
	(persona-necesita-contenido persona94 food)
	(loc-persona persona94 Loc60)
	(caja-contenido caja96 food)
	(loc-caja caja96 deposito)
	(persona-necesita-contenido persona95 food)
	(loc-persona persona95 Loc88)
	(caja-contenido caja97 food)
	(loc-caja caja97 deposito)
	(persona-necesita-contenido persona96 food)
	(loc-persona persona96 Loc13)
	(caja-contenido caja98 food)
	(loc-caja caja98 deposito)
	(persona-necesita-contenido persona97 food)
	(loc-persona persona97 Loc49)
	(caja-contenido caja99 food)
	(loc-caja caja99 deposito)
	(persona-necesita-contenido persona98 food)
	(loc-persona persona98 Loc93)
	(caja-contenido caja100 food)
	(loc-caja caja100 deposito)
	(persona-necesita-contenido persona99 food)
	(loc-persona persona99 Loc47)
	(caja-contenido caja101 food)
	(loc-caja caja101 deposito)
	(persona-necesita-contenido persona100 food)
	(loc-persona persona100 Loc87)
	(caja-contenido caja102 food)
	(loc-caja caja102 deposito)
	(persona-necesita-contenido persona101 food)
	(loc-persona persona101 Loc105)
	(caja-contenido caja103 food)
	(loc-caja caja103 deposito)
	(persona-necesita-contenido persona102 food)
	(loc-persona persona102 Loc100)
	(caja-contenido caja104 food)
	(loc-caja caja104 deposito)
	(persona-necesita-contenido persona103 food)
	(loc-persona persona103 Loc9)
	(caja-contenido caja105 food)
	(loc-caja caja105 deposito)
	(persona-necesita-contenido persona104 food)
	(loc-persona persona104 Loc89)
	(caja-contenido caja106 food)
	(loc-caja caja106 deposito)
	(persona-necesita-contenido persona105 food)
	(loc-persona persona105 Loc86)
	(caja-contenido caja107 food)
	(loc-caja caja107 deposito)
	(persona-necesita-contenido persona106 food)
	(loc-persona persona106 Loc67)
	(caja-contenido caja108 food)
	(loc-caja caja108 deposito)
	(persona-necesita-contenido persona107 food)
	(loc-persona persona107 Loc28)
	(caja-contenido caja109 food)
	(loc-caja caja109 deposito)
	(persona-necesita-contenido persona108 food)
	(loc-persona persona108 Loc39)
	(caja-contenido caja110 food)
	(loc-caja caja110 deposito)
	(brazo-dron-free dron1 brazo1)
	(brazo-dron-free dron1 brazo2)
)
(:goal (and

	(loc-dron dron1 deposito)
	(persona-tiene-contenido persona0 food)
	(persona-tiene-contenido persona1 food)
	(persona-tiene-contenido persona2 food)
	(persona-tiene-contenido persona3 food)
	(persona-tiene-contenido persona4 food)
	(persona-tiene-contenido persona5 food)
	(persona-tiene-contenido persona6 food)
	(persona-tiene-contenido persona7 food)
	(persona-tiene-contenido persona8 food)
	(persona-tiene-contenido persona9 food)
	(persona-tiene-contenido persona10 food)
	(persona-tiene-contenido persona12 food)
	(persona-tiene-contenido persona13 food)
	(persona-tiene-contenido persona14 food)
	(persona-tiene-contenido persona15 food)
	(persona-tiene-contenido persona16 food)
	(persona-tiene-contenido persona17 food)
	(persona-tiene-contenido persona18 food)
	(persona-tiene-contenido persona19 food)
	(persona-tiene-contenido persona19 medicine)
	(persona-tiene-contenido persona20 food)
	(persona-tiene-contenido persona22 food)
	(persona-tiene-contenido persona23 food)
	(persona-tiene-contenido persona24 food)
	(persona-tiene-contenido persona25 food)
	(persona-tiene-contenido persona26 food)
	(persona-tiene-contenido persona27 food)
	(persona-tiene-contenido persona28 food)
	(persona-tiene-contenido persona29 food)
	(persona-tiene-contenido persona30 food)
	(persona-tiene-contenido persona31 food)
	(persona-tiene-contenido persona32 food)
	(persona-tiene-contenido persona33 food)
	(persona-tiene-contenido persona34 food)
	(persona-tiene-contenido persona34 medicine)
	(persona-tiene-contenido persona35 food)
	(persona-tiene-contenido persona36 food)
	(persona-tiene-contenido persona37 food)
	(persona-tiene-contenido persona38 food)
	(persona-tiene-contenido persona39 food)
	(persona-tiene-contenido persona40 food)
	(persona-tiene-contenido persona41 food)
	(persona-tiene-contenido persona42 food)
	(persona-tiene-contenido persona43 food)
	(persona-tiene-contenido persona44 food)
	(persona-tiene-contenido persona45 food)
	(persona-tiene-contenido persona46 food)
	(persona-tiene-contenido persona47 food)
	(persona-tiene-contenido persona48 food)
	(persona-tiene-contenido persona49 food)
	(persona-tiene-contenido persona50 food)
	(persona-tiene-contenido persona51 food)
	(persona-tiene-contenido persona52 food)
	(persona-tiene-contenido persona53 food)
	(persona-tiene-contenido persona54 food)
	(persona-tiene-contenido persona55 food)
	(persona-tiene-contenido persona56 food)
	(persona-tiene-contenido persona57 food)
	(persona-tiene-contenido persona58 food)
	(persona-tiene-contenido persona58 medicine)
	(persona-tiene-contenido persona59 food)
	(persona-tiene-contenido persona60 food)
	(persona-tiene-contenido persona61 food)
	(persona-tiene-contenido persona62 food)
	(persona-tiene-contenido persona63 food)
	(persona-tiene-contenido persona64 food)
	(persona-tiene-contenido persona65 food)
	(persona-tiene-contenido persona66 food)
	(persona-tiene-contenido persona67 food)
	(persona-tiene-contenido persona68 food)
	(persona-tiene-contenido persona69 food)
	(persona-tiene-contenido persona71 food)
	(persona-tiene-contenido persona72 food)
	(persona-tiene-contenido persona72 medicine)
	(persona-tiene-contenido persona73 food)
	(persona-tiene-contenido persona74 food)
	(persona-tiene-contenido persona75 food)
	(persona-tiene-contenido persona76 food)
	(persona-tiene-contenido persona77 food)
	(persona-tiene-contenido persona78 food)
	(persona-tiene-contenido persona79 food)
	(persona-tiene-contenido persona80 food)
	(persona-tiene-contenido persona81 food)
	(persona-tiene-contenido persona82 food)
	(persona-tiene-contenido persona83 food)
	(persona-tiene-contenido persona84 food)
	(persona-tiene-contenido persona85 food)
	(persona-tiene-contenido persona86 food)
	(persona-tiene-contenido persona87 food)
	(persona-tiene-contenido persona88 food)
	(persona-tiene-contenido persona89 food)
	(persona-tiene-contenido persona90 food)
	(persona-tiene-contenido persona91 food)
	(persona-tiene-contenido persona92 food)
	(persona-tiene-contenido persona93 food)
	(persona-tiene-contenido persona94 food)
	(persona-tiene-contenido persona95 food)
	(persona-tiene-contenido persona96 food)
	(persona-tiene-contenido persona97 food)
	(persona-tiene-contenido persona98 food)
	(persona-tiene-contenido persona99 food)
	(persona-tiene-contenido persona100 food)
	(persona-tiene-contenido persona101 food)
	(persona-tiene-contenido persona102 food)
	(persona-tiene-contenido persona103 food)
	(persona-tiene-contenido persona104 food)
	(persona-tiene-contenido persona105 food)
	(persona-tiene-contenido persona106 food)
	(persona-tiene-contenido persona107 food)
	(persona-tiene-contenido persona108 food)
	))
)
