(define (problem drone_problem_d1_r0_l10_p10_c10_g10_ct2)(:domain logisticaSE)
(:objects
	dron1 - dron
	deposito - loc
	A - loc
	B - loc
	C - loc
	D - loc
	E - loc
	F - loc
	G - loc
	H - loc
	I - loc
	J - loc
	caja1 - caja
	caja2 - caja
	caja3 - caja
	caja4 - caja
	caja5 - caja
	caja6 - caja
	caja7 - caja
	caja8 - caja
	caja9 - caja
	caja10 - caja
	food - contenido
	medicine - contenido
	persona0 - persona
	persona1 - persona
	persona2 - persona
	persona3 - persona
	persona4 - persona
	persona5 - persona
	persona6 - persona
	persona7 - persona
	persona8 - persona
	persona9 - persona
	brazo1 - brazo
	brazo2 - brazo)
(:init
	(loc-dron dron1 J)
	(persona-necesita-contenido persona0 food)
	(loc-persona persona0 J)
	(caja-contenido caja1 food)
	(loc-caja caja1 H)
	(persona-necesita-contenido persona0 medicine)
	(loc-persona persona0 F)
	(caja-contenido caja2 medicine)
	(loc-caja caja2 J)
	(persona-necesita-contenido persona2 medicine)
	(loc-persona persona2 deposito)
	(caja-contenido caja3 medicine)
	(loc-caja caja3 C)
	(persona-necesita-contenido persona5 food)
	(loc-persona persona5 deposito)
	(caja-contenido caja4 food)
	(loc-caja caja4 deposito)
	(persona-necesita-contenido persona5 medicine)
	(loc-persona persona5 I)
	(caja-contenido caja5 medicine)
	(loc-caja caja5 A)
	(persona-necesita-contenido persona6 food)
	(loc-persona persona6 G)
	(caja-contenido caja6 food)
	(loc-caja caja6 I)
	(persona-necesita-contenido persona6 medicine)
	(loc-persona persona6 G)
	(caja-contenido caja7 medicine)
	(loc-caja caja7 F)
	(persona-necesita-contenido persona7 medicine)
	(loc-persona persona7 J)
	(caja-contenido caja8 medicine)
	(loc-caja caja8 F)
	(persona-necesita-contenido persona8 medicine)
	(loc-persona persona8 E)
	(caja-contenido caja9 medicine)
	(loc-caja caja9 F)
	(persona-necesita-contenido persona9 food)
	(loc-persona persona9 A)
	(caja-contenido caja10 food)
	(loc-caja caja10 J)
	(brazo-dron-free dron1 brazo1)
	(brazo-dron-free dron1 brazo2)
)
(:goal (and

	(loc-dron dron1 deposito)
	(persona-tiene-contenido persona0 food)
	(persona-tiene-contenido persona0 medicine)
	(persona-tiene-contenido persona2 medicine)
	(persona-tiene-contenido persona5 food)
	(persona-tiene-contenido persona5 medicine)
	(persona-tiene-contenido persona6 food)
	(persona-tiene-contenido persona6 medicine)
	(persona-tiene-contenido persona7 medicine)
	(persona-tiene-contenido persona8 medicine)
	(persona-tiene-contenido persona9 food)
	))
)
