(define (problem problemaBasico2) (:domain logisticaSE)
(:objects 
    persona1 persona2 persona3 persona4 - persona
    caja1 caja2 caja3 caja4 - caja
    comida medicina bebida - contenido
    A B C D deposito - loc
    dron1 dron2 - dron
    transportador1 transportador2 - transportador
)

(:init
    (persona-necesita-contenido persona1 comida)
    (persona-necesita-contenido persona2 bebida)
    (persona-necesita-contenido persona3 medicina)
    (persona-necesita-contenido persona4 comida)
    (loc-caja caja1 deposito)
    (loc-caja caja2 deposito)
    (loc-caja caja3 deposito)
    (loc-caja caja4 deposito)
    (caja-free caja1)
    (caja-free caja2)
    (caja-free caja3)
    (caja-free caja4)
    (loc-persona persona1 A)
    (loc-persona persona2 C)
    (loc-persona persona3 B)
    (loc-persona persona4 D)
    (loc-dron dron1 deposito)
    (loc-dron dron2 deposito)
    (caja-contenido caja1 comida)
    (caja-contenido caja2 medicina)
    (caja-contenido caja3 bebida)
    (caja-contenido caja4 comida)
    (loc-transportador transportador1 deposito)
    (loc-transportador transportador2 deposito)
    (dron-free dron1)
    (dron-free dron2)
    (=(capacidad-transportador transportador1) 4)
    (=(capacidad-transportador transportador2) 4)
	(=(fly-cost deposito A ) 100)
	(=(fly-cost deposito B ) 150)
	(=(fly-cost deposito C ) 2000)
	(=(fly-cost A deposito ) 100)
	(=(fly-cost B deposito ) 150)
	(=(fly-cost C deposito ) 2000)
    (=(fly-cost D deposito ) 750)
	(=(fly-cost A B ) 50)
	(=(fly-cost B A ) 50)
	(=(fly-cost A C ) 300)
	(=(fly-cost C A ) 300)
	(=(fly-cost B C ) 100)
	(=(fly-cost C B ) 100)
    (=(fly-cost A D ) 500)
    (=(fly-cost B D ) 250)
    (=(fly-cost C D ) 300)
    (=(fly-cost deposito deposito ) 1)
    (=(fly-cost A A) 1)
    (=(fly-cost B B) 1)
    (=(fly-cost C C) 1)
    (=(fly-cost D D) 1)
)

(:goal (and
    (loc-dron dron1 deposito)
	(loc-dron dron2 deposito)
    (persona-tiene-contenido persona1 comida)
    (persona-tiene-contenido persona2 bebida)
    (persona-tiene-contenido persona3 medicina)
    (persona-tiene-contenido persona4 comida)
))

;uncomment if use
;(:metric minimize (coste-total))
)